spring:
  application:
    name: spring-security-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/liuqitech
    username: root
    password: 676110
    driver-class-name: com.mysql.cj.jdbc.Driver